CREATE DATABASE IF NOT EXISTS quick_messages;

USE quick_messages;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password TEXT NOT NULL,
  image TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  level TINYINT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1
);